Updates to About Page
GTHC/web pull request #104
Opened 2019-12-25 23:11 UTC by Akhan221

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-12-25 23:45 UTC, amanmibra requested changes
Good work, just make these small changes, and ping me when you finished them. :+1:

2019-12-25 23:45 UTC, amanmibra commented on app/javascript/src/containers/About.jsx
> +<br></br><br></br>
Fix the alignment of these lines. Tab them into place.

2019-12-25 23:45 UTC, amanmibra commented on app/javascript/src/containers/About.jsx
> +                <h2>The story of GTHC begins in February 2018 when Aman Ibrahim, then a Duke sophomore, experienced his first tenting season awaiting the Duke vs. UNC men's basketball game. Two weeks
Use a `p` (paragraph) element instead of `h2`

2019-12-25 23:45 UTC, amanmibra commented on app/javascript/src/containers/About.jsx
> +            content="What is GTHC?"
Switch "What is GTHC?" and "Origins of GTHC"

2019-12-25 23:45 UTC, amanmibra commented on app/javascript/src/containers/AboutUs.jsx
> +                      Team Member
Change "Team Member" and "Tern" to either "Developer", "Marketing", or "Junior Developer"

2019-12-25 23:45 UTC, amanmibra commented on config/routes.rb
> +  # get 'about/aboutus', to: 'about#aboutus'
remove these comments

2019-12-26 18:53 UTC, Akhan221 commented
Made changes to the about pages as requested, however the console keeps giving the following warning for the image alignment despite troubleshooting: 

Received `true` for a non-boolean attribute `centered`

2019-12-29 17:55 UTC, amanmibra approved these changes
Good Work! Congrats on your first official GTHC PR! 👍 💯 🥇

2019-12-29 17:56 UTC, merged