WIP: Updated Tenting101
GTHC/web pull request #43
Opened 2018-12-28 08:16 UTC by rikkikendall

Purpose
The overall purpose of this PR is for the Tenting101 section at the top of the login page. 

Tasks
Create stepper for Tenting101.
Also involves gathering information from Policy Changes to include the Line Monitor Tent Registration
and Tenting Dates/Information.

Test
How to test:
Run yarn dev:start
Try the Tenting101 feature at the top of the login page.
More info for testing coming...

2018-12-28 12:38 UTC, amanmibra commented
Hey, before I do the review, I notices your commit messages, and I thought I would share this with you:
https://github.com/agis/git-style-guide#commits

This goes over basic conventions of many git practices, including commits and commit messages. Read it and follow it and it'll be very helpful in the future going forward.

2018-12-28 12:41 UTC, amanmibra commented
Also, did the PR template not show up for you when you made the PR? Please use it for any PRs from now on: 

Go ahead and update your message above with the following (just copy and paste):
```
<!--- Provide a general summary of your changes in the Title above -->

## Description
<!--- Describe your changes in detail -->

## Motivation and Context
<!--- Why is this change required? What problem does it solve? -->
<!--- If it fixes an open issue, please link to the issue here. -->

## How Has This Been Tested?
<!--- Please describe in detail how you tested your changes. -->
<!--- Include details of your testing environment, and the tests you ran to -->
<!--- see how your change affects other areas of the code, etc. -->

## Screenshots (if appropriate):

## Types of changes
<!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
```

2018-12-28 13:12 UTC, amanmibra requested changes
Looks good, just make the changes that I request, and also update your NavBar for the page. Once you do that just @ me and then you will prob be good to go! :+1:

2018-12-28 13:12 UTC, amanmibra commented on app/javascript/src/containers/Login.jsx
> -            clearError,
You removed an important redux action, clearError, during your merging, please add it back. When dealing with merge conflicts from staging, if it does not affect the feature you are working on, always keep the new code.

2018-12-28 13:12 UTC, amanmibra commented on app/javascript/src/containers/Login.jsx
> -      clearError: clearError,
Same thing, add this line back.

2018-12-28 13:12 UTC, amanmibra commented on app/javascript/src/containers/Login.jsx
> -            clearError,
Just add the same line back

2018-12-28 13:12 UTC, amanmibra commented on app/javascript/src/containers/Tenting101.jsx
> +    console.log('data', data);
Remove console.logs. Cannot have in production.

2018-12-28 13:12 UTC, amanmibra commented on app/javascript/src/containers/Tenting101.jsx
> +          </ div>
Lines 95-96
Can you remove that extra spacing between `</` and `Menu>`. Same thing for the `div` below it.

2018-12-28 13:12 UTC, amanmibra commented on app/javascript/src/components/tenting/Step1.jsx
> +       <Message centered header='Step 1' size='large' content='Find your tent members and establish a Tent Captain.'/>
`Message` does not have a centered prop. Please check docs to confirm props before using them as they throw errors or warnings (check your console, and you can see them).

2018-12-28 15:02 UTC, amanmibra commented
@rikkikendall Also, open your console and see the warnings your code is setting off. Work on getting rid of those as well.

2018-12-29 02:30 UTC, rikkikendall commented
Sounds great, should have implemented those changes. Now need to decide on design changes for NavBar on the top, whether that should be like the login with the white background or the homepage with the inverted blue.

2018-12-30 16:29 UTC, amanmibra approved these changes

2018-12-30 16:31 UTC, amanmibra commented
Good work @rikkikendall I have approved your PR, but please remember to always pull and merge staging by doing the following:

```
$ git pull
$ git pull origin staging
```

2018-12-30 16:31 UTC, merged