Suggestion widget vinit
GTHC/web pull request #47
Opened 2019-01-02 20:55 UTC by vinitbytheminute

Trello Card explaining Widget: 
## Description

## Motivation and Context

## How Has This Been Tested?
1. Log in or Create an Account 
2. Go to Home page and scroll down
3. Press on "Tenting Application Question and Feedback Form"
4. Press on Questions or Suggestions

## Screenshots (if appropriate):
<img width="1196" alt="screen shot 2019-01-02 at 12 54 41 pm" src="https://user-images.githubusercontent.com/44485851/50612085-a43ab800-0e8d-11e9-894d-876f2118444b.png">
<img width="702" alt="screen shot 2019-01-02 at 12 54 50 pm" src="https://user-images.githubusercontent.com/44485851/50612087-ab61c600-0e8d-11e9-8bbc-29af99972604.png">
<img width="712" alt="screen shot 2019-01-02 at 12 54 58 pm" src="https://user-images.githubusercontent.com/44485851/50612093-b157a700-0e8d-11e9-8771-5bac5331eb37.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-01-04 08:23 UTC, Abdulla-Shahid commented
Hey Vinit, 
Great Job on the Widget. So for the current design of the homepage, pending the addition of the upcoming game API/widget, the suggestion widget could fit great here, underneath the upcoming games widget (if we want to keep it on the home page): 

![49062819_652739508632575_3692222628040278016_n](https://user-images.githubusercontent.com/22209648/50679085-db18e700-0fcf-11e9-8518-e41816665b6f.png)

Let me know what you think, if you like it, I'll add it to the grid after I'm done working with Aman on the points widget!

2019-01-04 23:20 UTC, mafuvadze commented
- I think it looks very odd to have an embedded Google forms page in the website. I think it would be cleaner if you just redirected users trying to submit feedback to a separate page. 
- Maybe don't put the feedback widget on the home screen? I think it fits better as a footer link to another page. Or maybe as a nav bar tab.

2019-01-04 23:27 UTC, mafuvadze requested changes

2019-01-04 23:27 UTC, mafuvadze commented on app/javascript/src/components/home/HomeBody/FeedbackForm.jsx
> +    <strong> NOT </strong> on the Tenting Process itself. Please direct those questions to linemonitors@gmail.com
Make this email address a hotlink so they can email the line monitors by clicking on it

2019-01-04 23:27 UTC, mafuvadze commented on app/javascript/src/components/home/HomeBody/FeedbackForm.jsx
> +  { key: 'panel-1a', title: 'Suggestions', content:{content: <iframe src="https://docs.google.com/forms/d/e/1FAIpQLScPghAkeRi-Ey0JhWRc2xmuG5fn6TofbIf147gsgIjhsRnuCQ/viewform?embedded=true" width="500
- Use more descriptive keys instead of panel-1a/b
 - Minor nit, but one thing that helps with readability is splitting json entities into separate lines

2019-01-05 00:19 UTC, Vinitowinit commented on app/javascript/src/components/home/HomeBody/FeedbackForm.jsx
> +    <strong> NOT </strong> on the Tenting Process itself. Please direct those questions to linemonitors@gmail.com
Great suggestion. Just linked it

2019-01-05 00:28 UTC, Vinitowinit commented on app/javascript/src/components/home/HomeBody/FeedbackForm.jsx
> +  { key: 'panel-1a', title: 'Suggestions', content:{content: <iframe src="https://docs.google.com/forms/d/e/1FAIpQLScPghAkeRi-Ey0JhWRc2xmuG5fn6TofbIf147gsgIjhsRnuCQ/viewform?embedded=true" width="500
1. I adjusted so that the key values are more descriptive. Thank you for the suggestion
2. I split the JSON entities as you requested.

2019-01-05 00:30 UTC, Vinitowinit commented
@mafuvadze I do see your point of view of having a widget for this may seem strange. I am open to any suggestions. I like it in the grid portion in the home page @Abdulla-Shahid is creating. I am open to anything. I guess we can talk about this the next meeting in a day or so and finalize this up.

2019-01-06 01:32 UTC, mafuvadze approved these changes
Great work

2019-01-06 03:38 UTC, amanmibra commented
I can resolve the conflicts on free time

2019-01-06 15:13 UTC, amanmibra requested changes
Vinit, I made some changes myself that you should look at. First, I made some code structure changes. Fixed some syntax, spacing, etc. Then, I decided it would best that we did not use `iframe` components for any component running on our app. This is because iframes are notoriously known for hindering performance and they look really ugly on our page as well tbh, so, I have replaced them with buttons. It doesn't have to buttons, but buttons was the only good alternative I could think of.

Go ahead and take a look at my most recent commit (just scroll up and click the recent commit message to see the changes of that commit **ONLY**) to see the exact change I made.

Once you decide which alternative you will use to iframes, whether it is buttons or not (as long as it opens the form on a separate page), please remove all of the lines of code that you had related to iframes.

2019-01-06 15:14 UTC, amanmibra commented
The widget with buttons

![image](https://user-images.githubusercontent.com/13587407/50737897-dbfe7400-119b-11e9-9bf9-6591cc0fc2c3.png)

2019-01-07 00:20 UTC, amanmibra approved these changes
Looks good, but change one more thing! I added a comment.

2019-01-07 00:20 UTC, amanmibra commented on app/javascript/src/components/home/HomeBody/widgets/FeedbackForm.jsx
>  const level1Content = (
Do not forget to remove this

2019-01-07 01:01 UTC, merged